%% This is intendend to be used as a child document to deforestation.Rnw
%% It will create a SF object with administrative divisions needed by deforestation.Rnw

%% if dhs.grid.RDS exists, it will not create it by running a full DHS harmonisation cycle.
%% if dhs.grid.RDS does not exist, make sure to install the package `globallivingconditions`
%% before trying to run its child document dhs-debug-child.Rnw

<<grid-creation-opts.chunk.parent, echo = FALSE>>=
opts_chunk$set(results='hide', cache=TRUE, echo=FALSE, warning=FALSE,
fig.width=4, fig.height=4, fig.pos = 'htb', tidy.opts=list(blank=FALSE,
width.cutoff=50), background='white', tidy=TRUE, error=TRUE, message=FALSE,
dev="png", dpi = 200, autodep = TRUE)
opts_knit$set(root.dir = ".")
options(scipen=999) ## Avoid scientific formating of large numbers.
@ 

<<grid-creation-install.globallivingconditions>>=
library(devtools)
install_bitbucket(repo = "hansekbrand/iwi")
install_bitbucket(repo = "hansekbrand/DHSharmonisation", upgrade = "never", ref = "debug")
@ 

<<grid-creation-load.data.using.child.document, child=system.file("dhs-debug-child.Rnw", package="globallivingconditions"), eval = FALSE>>=
@ 

<<grid-creation-setup.more>>=
deforestation.common.path <- paste0("Deforestation and poverty ",
                                    "- Forest coverage/")
gis.path.sf.common.path <- paste0("Deforestation and poverty - ",
                                  "DHS/GIS-borders-SF/")
country.data.path <- paste0("~/annex/projekt/",
      "global-living-conditions/stora-eller-statiska-filer/",
      "deforestation/Country data/")

if(file.exists("/mnt/windows")) {
    laptop.common <- paste0("/mnt/windows/")
    deforestation.path <- paste0(laptop.common,
                                 deforestation.common.path)
    gis.path.sf <- paste0(laptop.common, gis.path.sf.common.path)
}

if(file.exists("/mnt/c")) {
    laptop.common <- paste0("/mnt/c/Users/xekbha/",
      "University of Gothenburg/")
    deforestation.path <- paste0(laptop.common,
                                 deforestation.common.path)
    gis.path.sf <- paste0(laptop.common, gis.path.sf.common.path)
}

if(file.exists("/media/sf_Our_data")) {
    server.common <- paste0("/media/sf_Our_data/Hans/Onedrive/",
      "University of Gothenburg/")
    deforestation.path <- paste0(server.common,
                                 deforestation.common.path)
    gis.path.sf <- paste0(server.common, gis.path.sf.common.path)    
}

if(file.exists("~/mnt/poverty/media/sf_Our_data")) {
    server.common <- paste0("~/mnt/poverty/media/sf_Our_data/Hans/Onedrive/",
      "University of Gothenburg/")
    deforestation.path <- paste0(server.common,
                                 deforestation.common.path)
    gis.path.sf <- paste0(server.common, gis.path.sf.common.path)    
}

if(file.exists("/mimer/NOBACKUP/groups/globalpoverty1/")) {
    deforestation.path <- paste0("/mimer/NOBACKUP/groups/",
                                 "globalpoverty1/hans/Deforestation/")
    country.data.path <- paste0(deforestation.path,
                                "Country data/")
}

@

<<grid-creation-install.packages>>=
required.packages <- c("httr", "data.table", "car", "sp", "raster", "devtools",
                     "purrr", "doParallel", "snow", "viridisLite", "geosphere",
                     "parallel", "foreach", "tmap", "terra", "sf", "lme4",
                     "future.apply",
                       "parallelly", "readxl", "benchmarkme", "filelock")
for(package in required.packages){
    if(! require(package, character.only=TRUE)){
        install.packages(package, character.only=TRUE)
    }
}
library(devtools)
devtools::install_github("matthewkling/colors3d")
@

<<grid-creation-borders>>=
get.border <- function(country.code) {
  string.code <- globallivingconditions::iso.3166$String.code[
    match(country.code, globallivingconditions::iso.3166$numeric)
  ]
  filename <- file.path(gis.path.sf, paste0("gadm41_", string.code, "_0.rds"))
  if (file.exists(filename)) {
    return(readRDS(filename))
  } else {
    return(NULL)
  }
}

@ 

<<grid-creation-code.from.name>>=
code.from.name <- function(name) {
    globallivingconditions::iso.3166$numeric[match(name,
                    globallivingconditions::iso.3166$String)]
}
@ 

<<grid-creation-get.more.borders.select.south.america>>=
library(sf)
dir.create(gis.path.sf, showWarnings = FALSE, recursive = TRUE)

## make sure all borders exists

my.borders.inner.f <- function(code, gis.path.sf, absolute.log.filename, level) {
    ## code is the three letter code.
    ## While only the geometry corresponding to level 0 will be returned,
    ## the other levels, if they exist, will be saved to disk.

    my.log.f(paste(Sys.time(), "my.borders.inner.f called with argument", code), absolute.log.filename)
    ## if the file does not exists, then download it

    base.uri.for.gadm <- "https://geodata.ucdavis.edu/gadm/gadm4.1/json/"

    ## Start with level == 0
    ## code is the three letter code, eg. "ARG" for Argentine
    target.filename.base <- paste0("gadm41_", code, "_", 0)
    url.file <- paste0(target.filename.base, ".json")
    disk.file <- paste0(target.filename.base, ".rds")
    
    if(file.exists(paste0(gis.path.sf, disk.file)) == FALSE) {
        ## Look for an indication that this file does not exist at all.
        if(file.exists(paste0(gis.path.sf, disk.file, "does.not.exist"))) {
            ## No level zero file exists at all
            return(NULL)
        }

        ## Seems gadm has removed support for unzipped geo-json.ne
        hacked.url <- paste0("/vsizip//vsicurl/", base.uri.for.gadm, url.file, ".zip/", target.filename.base, ".json")
        my.error <- try(my.sf.df <- st_read(hacked.url, quiet = TRUE), silent = TRUE)        
        ## my.error <- try(my.sf.df <- st_read(paste0(base.uri.for.gadm, url.file), quiet = TRUE), silent = TRUE)
        if(length(attr(my.error, which = "condition")) > 0) {
            my.log.f(paste(Sys.time(), "no level", 0, "file for", code, "at", paste0(base.uri.for.gadm, url.file),
                           "sleeping to avoid bandwidth limiting measures"), absolute.log.filename)

            ## Make a local note of this.
            file.create(paste0(gis.path.sf, disk.file, "does.not.exist"))

            ## This was level 0, since it did no exist, just return NULL directly.
            return(NULL)
            
        } else {
            my.log.f(paste(Sys.time(), "border successfully downloaded for level 0", code), absolute.log.filename)
            saveRDS(my.sf.df, file = paste0(gis.path.sf, disk.file))
        }
    } else {
        my.log.f(paste(Sys.time(), "border exists locally for level 0", code), absolute.log.filename)
        my.sf.df <- readRDS(paste0(gis.path.sf, disk.file))
    }
    number.of.tries <- 0
    success <- FALSE
    while(level > 0) {
        target.filename.base <- paste0("gadm41_", code, "_", level)
        url.file <- paste0(target.filename.base, ".json")
        disk.file <- paste0(target.filename.base, ".rds")
        if(! file.exists(paste0(gis.path.sf, disk.file))) {
            if(file.exists(paste0(gis.path.sf, disk.file, "does.not.exist"))) {
                level <- level - 1
                next
            }
            number.of.tries <- number.of.tries + 1
            ## Seems gadm has removed support for unzipped geo-json recently
            hacked.url <- paste0("/vsizip//vsicurl/", base.uri.for.gadm, url.file, ".zip/", target.filename.base, ".json")
            my.error <- try(my.sf.df.subnational <- st_read(hacked.url, quiet = TRUE), silent = TRUE)        
            if(length(attr(my.error, which = "condition")) > 0) {
                if(success) {
                    ## File is there, try this level again, unless we have already tried the max number of times
                    my.log.f(paste(Sys.time(), "download failed at try number", number.of.tries,
                              "for this URI: ", paste0(base.uri.for.gadm, code, "_", level, "_sp.rds"),
                              "sleeping ", 61 * number.of.tries, "seconds"), absolute.log.filename)

                    ## biogeo.ucdavis.edu is unfortunately not reliable, 
                    ## increase the probability of getting a file by sleeping an increasing time for each attempt
                    Sys.sleep(1 * number.of.tries)
                    
                    if(number.of.tries >= 3) {
                        ## Give up on this one
                        file.create(paste0(gis.path.sf, disk.file, "does.not.exist"))
                        level <- level - 1
                    }
                } else {
                    my.log.f(paste(Sys.time(), "no level", level, "file for", code, "at",
                                   paste0(base.uri.for.gadm, url.file)), absolute.log.filename)
                    ## Don't try this level again
                    file.create(paste0(gis.path.sf, disk.file, "does.not.exist"))
                    level <- level - 1
                }
            } else {
                success <- TRUE
                my.log.f(paste(Sys.time(), "border successfully downloaded for level", level, code), absolute.log.filename)
                saveRDS(my.sf.df.subnational, file = paste0(gis.path.sf, disk.file))
                ## Good, move on to next level
                level <- level - 1
            }
        } else {
            success <- TRUE            
            my.log.f(paste(Sys.time(), "border exists locally for level", level, code), absolute.log.filename)
            ## Good, move on to next level
            level <- level - 1
        }
    }
    return(my.sf.df)
}

@

<<grid-creation-temp.create.list.of.all.desired.countries>>=
library(globallivingconditions)
library(sf); library(sp)
## based on dhs.grid (the sp object)
dhs.grid <- readRDS("/mnt/windows/Deforestation and poverty - Paper I/dhs.grid.RDS")
dhs.ones <- iso.3166$String.code[match(unique(sapply(strsplit(names(dhs.grid), split = ".", fixed = TRUE), function(x) { x[1]})), iso.3166$numeric)]

dhs.grid.sf <- st_as_sf(dhs.grid)
dhs.grid.sf$region <- names(dhs.grid)
dhs.grid.sf <- dhs.grid.sf[c("region", "geometry")]

m49 <- setDT(read.csv(system.file("M49.csv", package="globallivingconditions")))

## South America
south.america.letter.codes.tmp <- m49$ISO.alpha3.Code[which(m49$Sub.region.Name == "Latin America and the Caribbean")]
## Discard some small islands.
small.islands <- c("AIA", "ATG", "ABW", "BHS", "BRB", "BES", "VGB", "CYM", "CUW", "DMA", "GLP", "MTQ", "MSR", "BLM", "KNA", "LCA", "MAF", "VCT", "SXM", "TCA", "VIR", "BVT", "FLK", "SGS")
south.america.letter.codes <- south.america.letter.codes.tmp[south.america.letter.codes.tmp %in% small.islands == FALSE]

## Africa
africa <- m49[Region.Name == "Africa", list(Country.or.Area, ISO.alpha3.Code)]
## filter out some islands
africa <- africa[-match(c("R\\u00E9union", "British Indian Ocean Territory", "Comoros", "French Southern Territories", "Mauritius", "Mayotte", "Seychelles", "Cabo Verde", "Saint Helena"), Country.or.Area), ]

## Asia (south + Kyrgyz republic, Tajikistan)
asia.letter.codes <- c(m49$ISO.alpha3.Code[m49$Sub.region.Name %in% c("Southern Asia", "South-eastern Asia")], "KGZ", "TJK", "PNG")

## Europe, only Albania.
europe.letter.codes <- "ALB"

all.desired.countries <- c(south.america.letter.codes, asia.letter.codes, africa$ISO.alpha3.Code, europe.letter.codes)
remaining.ones <- all.desired.countries[which(all.desired.countries %in% dhs.ones == FALSE)]

## my.borders <- sapply(remaining.ones, function(x) {
##     my.borders.inner.f(x, gis.path.sf, absolute.log.filename = "deforestation.log", level = 3)
## }, simplify = FALSE)
## names(my.borders) <- remaining.ones

all.borders <- Reduce(rbind, sapply(all.desired.countries, function(x) {
    my.borders.inner.f(x, gis.path.sf, absolute.log.filename = "deforestation.log", level = 3)
}, simplify = FALSE))
path.to.artifacts <- "/mnt/windows/Deforestation and poverty - Paper I/"
saveRDS(all.borders, file = file.path(path.to.artifacts, "all.borders.RDS"))

oplan <- future::plan()
on.exit(future::plan(oplan), add = TRUE)
workers = max(1L, future::availableCores() - 1L)
future::plan(future::multicore, workers = workers)

remaining.ones.as.one.object <- Reduce(rbind, future_lapply(remaining.ones, function(country.letter.code) {
    ## Hardcode level 1 for Thailand and Viet nam
    if(country.letter.code %in% c("THA", "VNM")) {
        ## This construct will use level 1 (both of these countries have 3 levels,
        ## 3:1[3] will give level 1
        index <- 3
    } else {
        ## Use lowest level by default
        index <- 1
    }
    this.file <- sort(list.files(path = gis.path.sf,
      pattern = paste0("gadm41_", country.letter.code, "_.*.rds$")),                                 
      decreasing = TRUE)[index]
    ## Some exceptions: Use level 1 for Thailand and Viet Nam
    tmp <- readRDS(paste0(gis.path.sf, this.file))
    ## Standardize the column structure.
    ## Standardize by keep only a single column, "region",
    ## based on the highest available level
    target.colum.name <- paste0("GID_", length(grep("GID_", colnames(tmp))) - 1)
    tmp$region <- tmp[[target.colum.name]]
    keep.these <- c("region", "geometry")
    for(column in colnames(tmp)){
        if(! column %in% keep.these) {
            tmp[[column]] <- NULL
        }
    }
    return(tmp)
}))

## st_crs(dhs.grid.sf) <- st_crs(remaining.ones.as.one.object)

full.grid <- rbind(dhs.grid.sf, remaining.ones.as.one.object)
saveRDS(full.grid, file = "/mnt/windows/Deforestation and poverty - Paper I/my.sf.RDS")

@

