\documentclass[aspectratio=169,xcolor=table,english]{beamer}
% \documentclass[xcolor=table,swedish]{beamer}
\usefonttheme{professionalfonts}
%% \usepackage{tikz}
\usepackage[english]{babel}
\usepackage{IEEEtrantools} % proper indentation for multi-line equations
\usepackage{lmodern}
\usepackage{booktabs}
\usepackage{varioref}
\usepackage{hyperref}
\usepackage{rotating}
\usepackage{graphicx}
\setbeamertemplate{navigation symbols}{}
\usepackage{colortbl}
\usepackage{natbib}
\usepackage{multirow}
\usepackage{array}
\usepackage{pdfpages}

\usepackage{animate} %% supports autoplay, but does not supports gif. For the regression intro.
% Link colors
\definecolor{linkcol}{HTML}{1155CC} % blå
% hyperref already loaded by beamer, use hypersetup{} to configure it.
\hypersetup{
  colorlinks=true,
  urlcolor=linkcol
}

\usepackage{tikz}
\usetikzlibrary{overlay-beamer-styles}
\usepackage[absolute,overlay]{textpos}

\usepackage[export]{adjustbox}

\newenvironment{changemargin}[2]{%
\begin{list}{}{%
\setlength{\topsep}{0pt}%
\setlength{\leftmargin}{#1}%
\setlength{\rightmargin}{#2}%
\setlength{\listparindent}{\parindent}%
\setlength{\itemindent}{\parindent}%
\setlength{\parsep}{\parskip}%
}%
\item[]}{\end{list}}

\begin{document}

<<methods-setup, echo=FALSE, warning=FALSE, message=FALSE>>=
opts_chunk$set(results='hide', cache=TRUE, echo=FALSE, warning=FALSE, message=FALSE, fig.width=4, fig.height=3, dev="tikz", opts_knit$set(root.dir = "."))
knit_hooks$set(crop=hook_pdfcrop)
@

\begin{frame}
  \frametitle{Data: sources and preparations}
  \begin{itemize}
  \item Sources we have used so far
  \item The datasets we have constructed so far
  \end{itemize}
\end{frame}

\begin{frame}
  \frametitle{Data sources used so far}
  \begin{table}[htb]
    \centering
    {
    \renewcommand{\arraystretch}{1.6} % increase row spacing
    \begin{tabular}[htb]{p{4cm}p{5cm}p{5cm}}
      Data source & Level & Content \\
      \midrule 
      Demographic and Health Surveys (DHS) & Individual, clustered to a single point in the local area & Data on living conditions \\
      World Bank & Country & Gross National Income \\
      Global Data Lab & Top level region & Gross National Income for Indian states \\
      Potapov et al. 2022 & Patches of land, $30 \times 30m^2$ & Land use \\
      GADM & Administrative divisions & Geometric boundaries \\
      \bottomrule
    \end{tabular}
    }
    \caption{Level, content and data source used.}
    \label{tab:sources}
  \end{table}
\end{frame}

\begin{frame}
  \frametitle{What we started out using, but decided against}
  \includegraphics[scale=0.1]{Hansen}
\end{frame}

\begin{frame}
  \frametitle{What we actually use}
  \includegraphics[scale=0.1]{Potapov}  
\end{frame}

\begin{frame}
  \frametitle{Administrative divisions, based on GADM, adopted for the DHS}
  \vspace{-1.0cm}
  \includegraphics[scale=0.1]{divisions} \\
  Some administrative divisions have been merged to get more areas with 3 data points from different DHS waves after 2000. Not all countries have DHS data, e.g. Brazil.
\end{frame}

\begin{frame}{Understanding the deforestation data source}
\begin{columns}[T,onlytextwidth]
  \begin{column}{0.5\textwidth}
  \includegraphics[scale=0.1]{understanding_the_source}
  \end{column}
  \begin{column}{0.5\textwidth}
    The numbers in the cells are codes the encode the classification of the cell. Codes 27-48 and 127-148 represent forest. \emph{Forest} is defined as ``area covered by organic structures (trees) that reflects sunlight at least 5 meters above the ground.''. \emph{Average forest coverage} is the number of forest cells divided by the total number of valid cells (excluding lakes etc) in the area.
  \end{column}
\end{columns}
\end{frame}

\begin{frame}
  \frametitle{The initial state of forest coverage}
  \includegraphics[scale=0.1]{initial-state}  
\end{frame}

\begin{frame}
  \frametitle{Data is aggregated to administrative regions}
\begin{columns}[T,onlytextwidth]
  \begin{column}{0.75\textwidth}
  \includegraphics[scale=0.2]{initial-state-zoom}  
  \end{column}
  \begin{column}{0.25\textwidth}
    Note that each administrative region only has a \emph{single} color, representing the \emph{average} forest coverage.
  \end{column}
\end{columns}
\end{frame}

\begin{frame}
  \includegraphics[scale=0.12]{current-state}  
\end{frame}

\begin{frame}
  \frametitle{Public disemination of our first dataset}
  ``Forest cover and change in low- and middle-income countries aggregated to administrative areas (2000–2020)'' \href{https://zenodo.org/records/19221532}{https://doi.org/10.5281/zenodo.19221532}. \\

  \vspace{0.5cm}

  \begin{quote}
    A dataset of forest cover and forest cover change for 2000–2020 in low- and middle-income countries, constructed by aggregating high-resolution satellite-derived land cover data to 35502 subnational administrative areas. These spatial units are socially and politically meaningful and designed to be compatible with geocoded household survey data from the Demographic and Health Surveys (DHS), while also supporting integration with other datasets.

The dataset includes baseline forest cover in 2000 and changes in forest cover at five-year intervals up to 2020. By eliminating the need for spatial data processing, it enables researchers to analyse deforestation and forest gain using standard statistical tools.
  \end{quote}
\end{frame}

\newcommand{\fullframeimage}[1]{%
  \begin{frame}[plain]
    \begin{tikzpicture}[remember picture,overlay]
      \node at (current page.center) {%
        \includegraphics[
          max size={\paperwidth}{\paperheight},
          keepaspectratio
        ]{#1}%
      };
    \end{tikzpicture}
  \end{frame}
}

\fullframeimage{zenodo}

\begin{frame}
  \frametitle{Features and limitations of the first dataset}
  \begin{itemize}
  \item It is adjusted to use with geocoded DHS data via the customised administrative divisions. Our R package \href{https://bitbucket.org/hansekbrand/dhsharmonisation/src/master/}{globallivingconditions} connects DHS data to these administrative divisions.
  \item It is available in two versions: with and without geometry data.
  \item The first published dataset only has data about forest coverage, no data about living conditions.
  \item It only contains data about changes in forest coverage, not changes in land use in general.
  \end{itemize}
\end{frame}

\begin{frame}
  \frametitle{Our second dataset: linking DHS data to deforestation data}
  \begin{itemize}
  \item Based on geocoded deforestation data for every fifth year from year 2000 up to 2020, and geocoded data on living conditions based on the DHS, construct a data set that includes an area average for household wealth index (IWI), GNI, and the change in forest coverage for the forthcoming five years.
  \item DHS is dated irregularly.
  \item Aggregating DHS measurements from different points in an area creates sampling noise.
  \item DHS adds a random offset to the coordinates, so some points end up in the wrong area.
  \item We estimate a trend of IWI development over time for all areas, and include the education of a fixed cohort to reduce sampling noise and improve the estimate.
  \end{itemize}
\end{frame}

\fullframeimage{impute-based-on-education}

\fullframeimage{impute-based-on-education-2}

\begin{frame}
\frametitle{Structure of the second data set (current version)}
% latex table generated in R 4.5.1 by xtable 1.8-4 package
% Fri May 29 00:48:35 2026
\begin{table}[ht]
  \centering
\resizebox{\textwidth}{!}{%  
\begin{tabular}{rlllrrrrr}
  \toprule
 & Country & Top level Region & Area name & year & IWI & GNI.log & FC & FCC \\ 
  \midrule
1 & Zimbabwe & Zimbabwe.Midlands & 716.Midlands.Chirumhanzu & 2000 & 17.86 & 7.26 & 8.21 & -0.17 \\ 
  2 & Zimbabwe & Zimbabwe.Midlands & 716.Midlands.Chirumhanzu & 2005 & 21.20 & 7.03 & 8.04 & -0.48 \\ 
  3 & Zimbabwe & Zimbabwe.Midlands & 716.Midlands.Chirumhanzu & 2010 & 24.55 & 7.41 & 7.56 & 0.28 \\ 
  4 & Zimbabwe & Zimbabwe.Midlands & 716.Midlands.Chirumhanzu & 2015 & 27.89 & 7.62 & 7.84 & -0.02 \\ 
  5 & Zimbabwe & Zimbabwe.Midlands & 716.Midlands.Gokwe North & 2000 & 12.32 & 7.26 & 19.53 & -0.56 \\ 
  6 & Zimbabwe & Zimbabwe.Midlands & 716.Midlands.Gokwe North & 2005 & 15.66 & 7.03 & 18.96 & -0.24 \\ 
  7 & Zimbabwe & Zimbabwe.Midlands & 716.Midlands.Gokwe North & 2010 & 19.00 & 7.41 & 18.72 & -0.43 \\ 
  8 & Zimbabwe & Zimbabwe.Midlands & 716.Midlands.Gokwe North & 2015 & 22.33 & 7.62 & 18.29 & -0.10 \\ 
  9 & Zimbabwe & Zimbabwe.Midlands & 716.Midlands.Gokwe South & 2000 & 16.50 & 7.26 & 15.94 & -0.39 \\ 
  10 & Zimbabwe & Zimbabwe.Midlands & 716.Midlands.Gokwe South & 2005 & 19.83 & 7.03 & 15.55 & -0.38 \\ 
  11 & Zimbabwe & Zimbabwe.Midlands & 716.Midlands.Gokwe South & 2010 & 23.16 & 7.41 & 15.17 & -0.60 \\ 
  12 & Zimbabwe & Zimbabwe.Midlands & 716.Midlands.Gokwe South & 2015 & 26.49 & 7.62 & 14.58 & -0.38 \\ 
   \bottomrule
\end{tabular}
}
\caption{Some data points for areas in a top level region in the merged dataset. 'FC' = 'Forest Coverage'; 'FCC' = 'Forest Coverage Change'. Note that the data is lagged, FCC is at $t+5$.} 
\label{tab:def1}
\end{table}

\end{frame}

\fullframeimage{kuznets.png}


\end{document}
